### ISSUE TITLE
Could not run 

### ISSUE THREAD

**Issue by adriancf-br** [SerdarHelli/Segmentation-of-Teeth-in-Panoramic-X-ray-Image#1]
Dear SerdarHelli,

First of all, thanks for this excelente work. Unfortunately, I could not run this code and I would appreciate a lot if you could give me the execution line command.

Thanks,
Adrian

**Comment by SerdarHelli** [comment]
Hello Adrian,
I will make the necessary adjustments and additions when this study is
published. But I can help you with your specific Question.

ADRIAN <notifications@github.com>, 17 Eki 2020 Cmt, 18:40 tarihinde şunu
yazdı:

**Comment by SerdarHelli** [comment]
Now , You can easily run with one click . Cheers 🚀 🚀 🚀
