### ISSUE TITLE
REQUEST to model.h5 file 

### ISSUE THREAD

**Issue by usmanyousaaf** [SerdarHelli/Segmentation-of-Teeth-in-Panoramic-X-ray-Image#10]
can you share a save model.h5 file due to computational cost will never train this again its a request just public the url of model.h5 file from your drive

**Comment by SerdarHelli** [comment]
You can find from there https://huggingface.co/SerdarHelli/Segmentation-of-Teeth-in-Panoramic-X-ray-Image-Using-U-Net
