### ISSUE TITLE
Cannot import error 

### ISSUE THREAD

**Issue by Subhankar27** [SerdarHelli/Segmentation-of-Teeth-in-Panoramic-X-ray-Image#7]
Hi, 

my kernel is crashing after this step every time
<img width="1256" alt="Screenshot 2023-03-16 at 21 15 49" src="https://user-images.githubusercontent.com/82767744/225684582-45ccddc2-d0ff-4644-ba49-3d80d8f5e15f.png">

**Comment by SerdarHelli** [comment]
Maybe you should check out your cpu/gpu memory. You can try on Colab
