### ISSUE TITLE
BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by sohaiblaraba** [SerdarHelli/Segmentation-of-Teeth-in-Panoramic-X-ray-Image#8]
Hello,

I'm trying to run your code but it seems that the link to download your data is not working.

I get the following error:

`BadZipFile                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_22420/3675071757.py in <module>
      4 if os.path.exists(path+'/DentalPanoramicXrays.zip') == False:
      5   os.makedirs(path, exist_ok=True)
----> 6   download_dataset(path+'/')

c:\Users\Sohaib\Documents\Velmini\NEW\codes\Segmentation-of-Teeth-in-Panoramic-X-ray-Image-Using-U-Net\download_dataset.py in download_dataset(save_path)
     13     r = requests.get("https://md-datasets-cache-zipfiles-prod.s3.eu-west-1.amazonaws.com/hxt48yk462-1.zip")
     14     print("Downloading...")
---> 15     z = ZipFile(BytesIO(r.content))
     16     z.extractall(save_path)
     17     print("Completed...")

c:\ProgramData\Anaconda3\lib\zipfile.py in __init__(self, file, mode, compression, allowZip64, compresslevel, strict_timestamps)
   1255         try:
   1256             if mode == 'r':
-> 1257                 self._RealGetContents()
   1258             elif mode in ('w', 'x'):
   1259                 # set the modified flag so central directory gets written

c:\ProgramData\Anaconda3\lib\zipfile.py in _RealGetContents(self)
   1322             raise BadZipFile("File is not a zip file")
   1323         if not endrec:
-> 1324             raise BadZipFile("File is not a zip file")
   1325         if self.debug > 1:
   1326             print(endrec)

BadZipFile: File is not a zip file`

Can you please give me a a link to your data?

**Comment by SerdarHelli** [comment]
Can you try again ? I made adjustments
