### ISSUE TITLE
BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by AsmaeKarmouchi** [SerdarHelli/Segmentation-of-Teeth-in-Panoramic-X-ray-Image#9]
<img width="439" alt="image" src="https://github.com/SerdarHelli/Segmentation-of-Teeth-in-Panoramic-X-ray-Image-Using-U-Net/assets/122885582/857d8faa-c619-4551-bda7-be2d8599c353">

**Comment by SerdarHelli** [comment]
you didnt download  the zip file . Download zip file

**Comment by SerdarHelli** [comment]
or use that pls https://huggingface.co/datasets/SerdarHelli/SegmentationOfTeethPanoramicXRayImages
